---
managed_service_catalog_data: https://raw.githubusercontent.com/integr8ly/managed-service-controller/managed-services-admin-v0.0.1/manifests/managed-service-operators.v0.0.1.configmap.yaml
managed_service_catalog_source: https://raw.githubusercontent.com/integr8ly/managed-service-controller/managed-services-admin-v0.0.1/manifests/managed-service-operators.v0.0.1.catalogsource.yaml
olm_namespace: kube-system